name: final1
description: Una aplicación Flutter para inicio de sesión con datos locales.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.12
  geolocator: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.6

flutter:
  assets:
    - assets/images/1339175.png
    - assets/images/1334071.png
    - assets/images/1345681.png
    - assets/images/1350379.png
    - assets/images/1350383.png


